import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { BulkUpsertSettingsDto, UpdateAttendanceRuleDto } from './dto/settings.dto';

/** Well-known setting keys the UI exposes; anything else is still readable/writable via the generic API. */
export const KNOWN_SETTING_DEFAULTS: Record<string, unknown> = {
  'system.name': 'ClassWeb',
  'theme.primaryColor': '#ff8a4c',
  'theme.secondaryColor': '#6fa3d6',
  'theme.mode': 'system',
  'pdf.header': '',
  'pdf.footer': 'Generated by ClassWeb · Official document',
};

@Injectable()
export class SettingsService {
  constructor(private readonly prisma: PrismaService) {}

  async list(universityId: string) {
    const rows = await this.prisma.setting.findMany({
      where: { universityId, scope: 'UNIVERSITY' },
      select: { key: true, value: true, description: true, updatedAt: true },
    });
    const byKey = new Map(rows.map((r) => [r.key, r]));
    // Merge in defaults for any known key that hasn't been set yet, so the UI always has a value to show.
    const merged = { ...KNOWN_SETTING_DEFAULTS };
    for (const [key, row] of byKey) merged[key] = row.value;
    return Object.entries(merged).map(([key, value]) => ({
      key, value, description: byKey.get(key)?.description ?? null, updatedAt: byKey.get(key)?.updatedAt ?? null,
    }));
  }

  async bulkUpsert(universityId: string, dto: BulkUpsertSettingsDto) {
    await this.prisma.$transaction(
      dto.settings.map((s) =>
        this.prisma.setting.upsert({
          where: { universityId_scope_scopeId_key: { universityId, scope: 'UNIVERSITY', scopeId: '', key: s.key } },
          update: { value: s.value as any, description: s.description },
          create: { universityId, scope: 'UNIVERSITY', scopeId: '', key: s.key, value: s.value as any, description: s.description },
        }),
      ),
    );
    return this.list(universityId);
  }

  // ---- Attendance rule (university-wide default) ------------------------

  async getAttendanceRule(universityId: string) {
    const rule = await this.prisma.attendanceRule.findFirst({
      where: { universityId, scope: 'UNIVERSITY', sectionId: null },
    });
    if (rule) return rule;
    // Materialise the default so the UI has a stable id to PATCH against.
    return this.prisma.attendanceRule.create({
      data: { universityId, scope: 'UNIVERSITY', name: 'Default attendance policy' },
    });
  }

  async updateAttendanceRule(universityId: string, dto: UpdateAttendanceRuleDto) {
    const rule = await this.getAttendanceRule(universityId);
    return this.prisma.attendanceRule.update({ where: { id: rule.id }, data: dto });
  }
}
